"""Root storage logic for issues and PRs (.coddy/issues/,
.coddy/pull_requests/)."""

from coddy.services.store.issue_store import (
    add_comment,
    create_issue,
    delete_comment,
    list_issues_by_status,
    list_pending_plan,
    list_queued,
    load_issue,
    mark_clarification_sent,
    save_issue,
    set_agent_clarification,
    set_issue_state,
    set_issue_status,
    update_comment,
)
from coddy.services.store.pr_store import (
    add_review,
    add_review_comment,
    delete_pending_pr_request,
    list_pending_pr_requests,
    list_prs_by_workflow_status,
    load_pr,
    save_pending_pr_request,
    save_pr,
    set_pr_status,
    set_pr_workflow_status,
)
from coddy.services.store.schemas import IssueComment, IssueFile, PendingPRRequest, PRFile, PRReview, PRReviewComment

__all__ = [
    "IssueComment",
    "IssueFile",
    "PendingPRRequest",
    "PRFile",
    "PRReview",
    "PRReviewComment",
    "add_comment",
    "add_review",
    "add_review_comment",
    "delete_pending_pr_request",
    "create_issue",
    "delete_comment",
    "list_issues_by_status",
    "list_pending_plan",
    "list_pending_pr_requests",
    "list_prs_by_workflow_status",
    "list_queued",
    "load_issue",
    "load_pr",
    "mark_clarification_sent",
    "save_issue",
    "save_pending_pr_request",
    "save_pr",
    "set_agent_clarification",
    "set_issue_state",
    "set_issue_status",
    "set_pr_status",
    "set_pr_workflow_status",
    "update_comment",
]
